name: ttii-chatbot
services:
- name: web
  source_dir: /
  github:
    repo: your-username/ttii-chatbot
    branch: main
  run_command: uvicorn main:app --host 0.0.0.0 --port 8080
  http_port: 8080
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET